config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "events#index"

  # setup events
  resources :events, only: [:index, :show] do

    # All posts of events ; like index
    collection do
      get :posts
    end

  end

  # setup user
  resources :users, only: [:show, :edit, :update]

  # setup interest
  resources :interests, only: [:create, :destroy] 

  # setup artist
  resources :artists, only: [:show] 

  # setup admin
  namespace :admin do
    root "events#index"
    resources :events, except: [:show, :new, :create] do 
      member do
        get :remove_artist
      end
    end
    
    resources :users, only: [:index, :destroy]
    resources :artists do 
      member do
        get :search
      end
    end
  end
  
end

app/models/event.rb
class Event < ApplicationRecord

  # 欄位驗證 :artist_name待補
  validates_presence_of :title, :date, :time, :stage

  # 一個event可以有很多筆被interest的資料
  has_many :interests, dependent: :destroy
  # 一個event可以被很多user interest
  has_many :interested_users, through: :interests, source: :user

  # 一個event可以有很多筆被view的資料
  has_many :views, dependent: :destroy
  # 一個event可以被很多user view
  has_many :viewed_users, through: :views, source: :user

  # 一個event可以有很多筆要notification的資料
  has_many :notifications, dependent: :destroy
  # 一個event可以對很多user送出notification
  has_many :notified_users, through: :notifications, source: :user

  # 一個活動目前設定只會顯示一筆藝人資料
  belongs_to :artist, optional: true

  # ransck
  STAGE = {
    'The Wall Live House': 'The Wall Live House',
    'Korner': 'Korner',
    'Revolver': 'Revolver',
    'PIPE Live Music': 'PIPE Live Music',
    'Legacy mini @ amba': 'Legacy mini @ amba',
    'Legacy 傳 音樂展演空間': 'Legacy 傳 音樂展演空間',
    '永豐 Legacy Taipei 音樂展演空間': '永豐 Legacy Taipei 音樂展演空間',
    'Legacy Taichung': 'Legacy Taichung',
    '公館河岸留言': '公館河岸留言',
    '河岸留言 音樂藝文咖啡': '河岸留言 音樂藝文咖啡',
    '台北 月見ル君想フ': '台北 月見ル君想フ'
  }

  CITY = {
    'Taichung': '台中',
    'Taipei': '台北',
  }

  def count_views
    self.views_count += 1
    self.save
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  
  before_action :set_event, only: [:edit, :update, :destroy, :remove_artist]

  ALLOW_QUERIES = %w[s artist_name_cont title_cont city_cont date_cont time_cont stage_eq stage_cont views_count interests_count detail_cont artist_name_or_title_or_city_or_detail_cont date_lteq date_gteq views_count_gteq interests_count_gteq updated_at].freeze

  def index
    @events = Event.all.order(date: :desc)
    # ransack
    @q = Event.ransack(ransack_params)
    @events = @q.result(distinct: true).order(updated_at: :desc).page(params[:page]).per(20)
  end

  def update
    if current_user.is_admin
      if @event.update_attributes(event_params)
        flash[:notice] = "Admin功能：更新活動頁面成功"
        redirect_to admin_events_path
      else
        render :action => :edit
      end
    else
      flash[:alert] = "非Admin，無此權限"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @event.destroy
  end

  def remove_artist
    @event.artist_name = nil
    @event.artist_id = nil
    @event.video = nil
    @event.spotify_artist_id = nil
    @event.save!
    redirect_back(fallback_location: root_path)
  end

  private 

  def ransack_params
    if params[:q].present?
      params.require(:q).permit(*ALLOW_QUERIES)
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:artist_name, :title, :date, :time, :stage, :video, :detail, :city, :stage, :spotify_artist_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  ALLOW_QUERIES = %w[s artist_name_cont title_cont city_cont date_cont time_cont stage_eq stage_cont views_count interests_count detail_cont artist_name_or_title_or_city_or_detail_or_stage_cont date_gteq date_lteq created_at city_eq].freeze

  def index
    # ransack
    @q = Event.ransack(ransack_params)
    @events = @q.result(distinct: true).order(date: :asc).page(params[:page]).per(12)

  end

  def show
    @event = Event.find(params[:id])

    # views count
    @event.count_views
    if current_user
      if current_user.viewed_events.include?(@event)
        @view = current_user.views.where(event_id: @event)
        @view.destroy_all
      end
      current_user.views.create(event_id: params[:id])
    end

    if @event.artist
      @artist = @event.artist
    else
      @artist = Artist.new
    end

  end

  def posts
    # ransack
    @q = Event.ransack(ransack_params)
    @events = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(5)
    @popular_events = Event.all.order(interests_count: :desc).limit(5)
  end

  private 

  def ransack_params
    if params[:q].present?
      params.require(:q).permit(*ALLOW_QUERIES)
    end
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/destroy.js.erb
$("#event-<%= @event.id %>").remove();

app/views/admin/events/edit.html.erb
<div class="container-fluid">
  
  <% if current_user.admin? %>
    <div class="userform">
      <h3>修改活動頁面資料</h3>
      <hr>
      <!-- errors msg //satrt -->
      <% if @event.errors.present? %>
        <% @event.errors.each do |error,message| %>
          <div class="alert alert-danger dismissable-alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <li><strong>WARNING</strong> : <%= "#{error.capitalize} #{message}" %></li>
          </div>
        <% end %>
        <hr><br />
      <% end %>
      <!-- errors msg //end -->
      
      <!-- user edit form //start-->
      <%= form_for [:admin, @event] do |f| %>
        <div class="form-group">
          
          <div class="field">
            <%= f.label :title %>
            <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "輸入活動名稱(必填)" %>
          </div><br />

          <div class="field">
            <%= f.label :artist_name %>
            <%= f.text_field :artist_name, class: "form-control", placeholder: "輸入演出者名稱(必填)" %>
          </div><br />

          <div class="field">
            <%= f.label :date %>
            <%= f.date_field :date, class: "form-control" %>
          </div><br />

          <div class="field">
            <%= f.label :time %> (<em>*註- 原來時間：<%= @event.time.slice(0..4) %></em>)
            <%= f.text_field :time,value: f.object.time.slice(0..4), class: "form-control" %>
          </div><br />

          <div class="field">
            <%= f.label :spotify_artist_id %>
            <%= f.text_field :spotify_artist_id, class: "form-control", placeholder: "輸入Spotify演出者ID" %>
          </div><br />

          <div class="field">
            <%= f.label :video %>
            <%= f.text_field :video, class: "form-control", placeholder: "輸入Youtube嵌入式影片網址" %>
          </div><br />

          <div class="field">
            <%= f.label :detail %>
            <%= f.text_area :detail, class: "form-control", placeholder: "輸入活動/演出介紹", rows: "12" %>
          </div><br />

          <div class="field">
            <%= f.label :city %>
            <%= f.text_field :city, class: "form-control", placeholder: "輸入活動所在城市" %>
          </div><br />

          <div class="field">
            <%= f.label :stage %>
            <%= f.text_field :stage, class: "form-control", placeholder: "輸入活動地點" %>
          </div><br />
          
          <div class="action">
            <%= f.submit "更新活動頁面", class: "btn btn-outline-primary"%>
            <%= f.button "取消變更", type: :reset, class: "btn btn-outline-secondary" %>
          </div>

        </div>
      <% end %>
      <!-- user edit form //end-->
      

    </div>
  <% else %>
    <div class="alert alert-danger dismissable-alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h2 class="text-center">非Admin無權瀏覽頁面資料</h2>
    </div>
    <hr>
  <% end %>


</div>

app/views/admin/events/index.html.erb
<div class="container-fluid">
  
  <div class="container-fluid">
    <div class="row">
      <!-- list //start -->
      <div class="col-md-10 col-sm-12">
        <!-- Tabs //start -->
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <%= link_to '表演活動清單', admin_events_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to '使用者清單', admin_users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '藝人清單', admin_artists_path, class: "nav-link" %>
          </li>
        </ul>
      
        <!-- Tabs //end -->
        
        <!-- Event list //start -->
        <table class="table table-responsive{sm,md}">
          <thead class="thead-light">
            <tr>
              <th scope="col"><%= sort_link(@q, :id, "#", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :date, "活動日期", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :updated_at, "更新時間", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :title, "活動名稱", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :time, "活動時間", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :artist_name, "演出者", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :city, "城市", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :stage, "地點", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :views_count, "瀏覽數", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :interests_count, "收藏數", default_order: :desc)%></th>
              <th scope="col">功能1</th>
              <th scope="col">功能2</th>
            </tr>
          </thead>
            
          <tbody>
            <% @events.each do |event| %>
              <tr id="event-<%= event.id %>" >
                <th scope="row"><%= event.id %></th>
                <td><%= event.date %></td>
                <td><%= event.updated_at.localtime.to_s(:db) %></td>
                <td><%= link_to event.title, event_path(event) %></td>
                <td><%= event.time.slice(0..4) %></td>
                <td>
                  <% if event.artist %>
                    <%= link_to event.artist_name, artist_path(event.artist) %>
                  <% else %>
                    <%= event.artist_name %>
                  <% end %>
                </td>
                <td><%= event.city %></td>
                <td><%= render partial: "shared/location", locals: {object: event} %></td>
                <td><%= event.views_count %></td>
                <td><%= event.interests_count %></td>
                <td><%= link_to '編輯', edit_admin_event_path(event), class: "btn btn-outline-primary" %></td>
                <td><%= link_to '刪除', admin_event_path(event), remote: true, method: :delete, data: {confirm: "ARE YOU SURE?"},class: "btn btn-outline-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <!-- Event list //end -->
      </div>
      <!-- list //end -->

      <!-- search //start -->
      <div class="col-md-2 col-sm-12">
        <h5>後台搜尋</h5><hr>
        <%= search_form_for @q, url: admin_events_path do |f| %>
          <%= f.label :title, '活動名稱:' %>
          <%= f.search_field :title_cont, class: "form-control" %><br />

          <%= f.label :artist_name, '演出者:' %>
          <%= f.search_field :artist_name_cont, class: "form-control" %><br />

          <%= f.label :stage, '地點:' %>
          <%= f.search_field :stage_cont, class: "form-control" %><br />

          <%= f.submit '搜尋', class: "btn btn-outline-secondary form-control"%><br /><hr>

          <h5>進階搜尋</h5><hr>

          <%= f.label :date, '起始日期:' %>
          <%= f.date_field :date_gteq, placeholder: "YYYY-MM-DD", :value => Time.now.strftime("%Y-%m-%d"), class: "form-control" %><br />

          <%= f.label :date, '至:' %>
          <%= f.date_field :date_lteq, placeholder: "YYYY-MM-DD", class: "form-control" %><br />

          <%= f.label :views_count, '瀏覽數大於：' %>
          <%= f.search_field :views_count_gteq, class: "form-control" %><br />

          <%= f.label :interests_count, '收藏數大於：' %>
          <%= f.search_field :interests_count_gteq, class: "form-control" %><br />

          <%= f.submit '搜尋', class: "btn btn-outline-secondary form-control"%>

        <% end %>
      </div><!-- search //end -->

      <div class="col-md-12"></div>
        <div class="paginate">
          <%= paginate @events %>
        </div>
      </div>

    </div><!-- .row //end -->

  </div><!-- .container-fluid //end -->
  
</div><!-- .container-fluid //end -->