config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "events#index"

  # setup events
  resources :events, only: [:index, :show] do

    # All posts of events ; like index
    collection do
      get :posts
    end

  end

  # setup user
  resources :users, only: [:show, :edit, :update]

  # setup interest
  resources :interests, only: [:create, :destroy] 

  # setup artist
  resources :artists, only: [:show] 

  # setup admin
  namespace :admin do
    root "events#index"
    resources :events, except: [:show, :new, :create] do 
      member do
        get :remove_artist
      end
    end
    
    resources :users, only: [:index, :destroy]
    resources :artists do 
      member do
        get :search
      end
    end
  end
  
end

app/models/artist.rb
class Artist < ApplicationRecord
  
  require 'rspotify'

  validates_presence_of :name
  validates_uniqueness_of :name
  # 一個藝人可以有很多活動
  has_many :events

  def get_spotify_data

    artist_name = self.name
    return if artist_name.blank?

    if Rails.env.development?
      # local用
      spotify_config = Rails.application.config_for(:spotify)
      client_id = spotify_config["client_id"]
      client_secret = spotify_config["client_secret"]
    elsif Rails.env.production?
      # heroku用
      client_id = ENV['SPOTIFY_CLIENT_ID']
      client_secret = ENV['SPOTIFY_CLIENT__SECRET']
    end

    RSpotify.authenticate("#{client_id}", "#{client_secret}")
    artist = RSpotify::Artist.search(artist_name)
    artist_data = artist.first
  end


  def check_event_artist

    @events = Event.all
    @events.each do |event|
      next if event.artist_name.present?

      if event.title.include?(self.name) || event.detail.include?(self.name)
        event.artist_name = self.name
        event.artist_id = self.id
        event.video = self.artist_video
        event.spotify_artist_id = self.artist_spotify_id
        event.save! 
      end
    end

  end


  def update_relative_events
    @events = self.events
    @events.each do |event|
      event.artist_name = self.name
      event.video = self.artist_video
      event.spotify_artist_id = self.artist_spotify_id
      event.save!
    end
    self.check_event_artist
  end


  def create_stream_data

    searching = self.name
    
    if Rails.env.development?
      # local用
      yt_config = Rails.application.config_for(:youtube)
      url = "https://www.googleapis.com/youtube/v3/search?part=snippet&key=#{yt_config["app_id"]}&q=#{searching}&type=video&maxResults=1"
    elsif Rails.env.production?
      # heroku用
      url = "https://www.googleapis.com/youtube/v3/search?part=snippet&key=#{ENV['YOUTUBE_APP_ID']}&q=#{searching}&type=video&maxResults=1"
    end

    response = RestClient.get(URI::encode(url))
    data = JSON.parse(response.body)
    if data["items"] != []
      id = data["items"][0]["id"]["videoId"]
      self.artist_video = "https://www.youtube.com/embed/#{id}?enablejsapi=1"
    end

    # spotify
    spotify_data = self.get_spotify_data
    if spotify_data == nil
      self.artist_spotify_id = nil
    else
      self.artist_spotify_id = spotify_data.id
    end
    self.save!

  end


  def check_stream_data(temp_video, temp_spotify_id)

    if temp_video.blank? && temp_spotify_id.blank?
      if self.artist_video.blank?
        searching = self.name
        
        if Rails.env.development?
          # local用
          yt_config = Rails.application.config_for(:youtube)
          url = "https://www.googleapis.com/youtube/v3/search?part=snippet&key=#{yt_config["app_id"]}&q=#{searching}&type=video&maxResults=1"
        elsif Rails.env.production?
          # heroku用
          url = "https://www.googleapis.com/youtube/v3/search?part=snippet&key=#{ENV['YOUTUBE_APP_ID']}&q=#{searching}&type=video&maxResults=1"
        end

        response = RestClient.get(URI::encode(url))
        data = JSON.parse(response.body)
        if data["items"] != []
          id = data["items"][0]["id"]["videoId"]
          self.artist_video = "https://www.youtube.com/embed/#{id}?enablejsapi=1"
        end

        if self.artist_spotify_id.blank?
          # spotify
          spotify_data = self.get_spotify_data
          if spotify_data.blank?
            self.artist_spotify_id = nil
          else
            self.artist_spotify_id = spotify_data.id
          end
        end
        self.save!
      elsif self.artist_spotify_id.blank?
        # spotify
        spotify_data = self.get_spotify_data
        if spotify_data.blank?
          self.artist_spotify_id = nil
        else
          self.artist_spotify_id = spotify_data.id
        end
        self.save!
      end
    end

  end

end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < Admin::BaseController

  before_action :set_artist, only: [:update, :edit, :destroy]

  ALLOW_QUERIES = %w[s created_at updated_at name_cont].freeze

  def index
    # ransack
    @q = Artist.ransack(ransack_params)
    @artists = @q.result(distinct: true).order(updated_at: :desc).page(params[:page]).per(20)

    if params[:id]
      @artist = Artist.find(params[:id])
    else
      @artist = Artist.new
    end

  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      @artist.create_stream_data
      @artist.check_event_artist
      redirect_back(fallback_location: admin_artists_path)
      flash[:notice] = "成功建立藝人資料"
    else
      @q = Artist.ransack(ransack_params)
      @artists = @q.result(distinct: true).order(updated_at: :desc).page(params[:page]).per(20)
      render :index
    end
  end

  def update

    temp_video = @artist.artist_video
    temp_spotify_id = @artist.artist_spotify_id

    if @artist.update(artist_params)
      redirect_back(fallback_location: admin_artists_path)
      flash[:notice] = "成功更新藝人資料"
    else
      @artists = Artist.all
      render :index
    end

    @artist.check_stream_data(temp_video, temp_spotify_id)
    @artist.update_relative_events
    @artist.check_event_artist
  end

  def destroy
    @artist.destroy
  end

  def search
    @artist = Artist.find(params[:id])
    @artist.create_stream_data
    @artist.update_relative_events
    redirect_back(fallback_location: admin_artists_path)
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def ransack_params
    if params[:q].present?
      params.require(:q).permit(*ALLOW_QUERIES)
    end
  end

  def artist_params
    params.require(:artist).permit(:name, :artist_video, :artist_spotify_id)
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: [:show]

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

end

app/helpers/admin/artists_helper.rb
module Admin::ArtistsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/admin/artists/destroy.js.erb
$("#artist-<%= @artist.id %>").remove();

app/views/admin/artists/index.html.erb
<div class="container-fluid">
  
  <div class="container-fluid">
    <div class="row">

      <!-- errors msg //satrt -->
      <% if @artist.errors.present? %>
        <div class="col-12">
          <% @artist.errors.each do |error,message| %>
            <div class="alert alert-danger dismissable-alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <li><strong>WARNING</strong> : <%= "#{error.capitalize} #{message}" %></li>
            </div>
          <% end %>
        </div>
        <hr><br />
      <% end %>

      <!-- list //start -->
      <div class="col-md-8 col-sm-12">
        <!-- Tabs //start -->
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <%= link_to '表演活動清單', admin_events_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '使用者清單', admin_users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '藝人清單', admin_artists_path, class: "nav-link active" %>
          </li>

        </ul>
      
        <!-- Tabs //end -->
        
        <!-- artist list //start -->
        <table class="table table-responsive{sm,md}">
          <thead class="thead-light">
            <tr>
              <th scope="col"><%= sort_link(@q, :id, "#", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :created_at, "建立時間", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :updated_at, "更新時間", default_order: :desc)%></th>
              <th scope="col"><%= sort_link(@q, :name, "藝人名稱", default_order: :desc)%></th>
              <th scope="col">功能1</th>
              <th scope="col">功能2</th>
            </tr>
          </thead>
            
          <tbody>
            <% @artists.each do |artist| %>
              <tr id="artist-<%= artist.id %>" >
                <th scope="row"><%= artist.id %></th>
                <td><%= artist.created_at.localtime.to_s(:db) %></td>
                <td><%= artist.updated_at.localtime.to_s(:db) %></td>
                <td><%= link_to artist.name, artist_path(artist) %></td>
                <td><%= link_to '編輯', admin_artists_path(id: artist.id), class: "btn btn-outline-primary" %></td>
                <td><%= link_to '刪除', admin_artist_path(artist), remote: true, method: :delete, data: {confirm: "ARE YOU SURE?"}, class: "btn btn-outline-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <!-- artist list //end -->
      </div>
      <!-- list //end -->

      
    

      <!-- search & create/update artist //start -->
      <div class="col-md-4 col-sm-12 text-center">
        <h5>新增/更新藝人名稱</h5><hr>
        <% if @artist.errors.any? %>
          <%= @artist.errors.full_messages.to_sentence %>
        <% end %>
        <%= form_for [:admin, @artist] do |f| %>
          <div class="form-group">
            <%= f.text_field :name, placeholder: "Artist Name",  class: "form-control" %><br />
            <% if params[:id] %>
              <%= f.text_field :artist_video, placeholder: "Artist Youtube Video",  class: "form-control" %><br />
              <%= f.text_field :artist_spotify_id, placeholder: "Artist Spotify ID",  class: "form-control" %><br />
            <% end %>
          </div>
          <%= f.submit class: "btn btn-outline-secondary" %><br />
          <br />
          <% if params[:id] %>
            <%= link_to "重新取得Stream Data", search_admin_artist_path(params[:id]), class: "btn btn-outline-secondary" %><br />
          <% end %>
        <% end %>
        <br />

        <h5>後台搜尋</h5><hr>
        <%= search_form_for @q, url: admin_artists_path do |f| %>
          <%= f.label :name, '藝人名稱:' %>
          <%= f.search_field :name_cont, class: "form-control" %><br />
          <%= f.submit '搜尋', class: "btn btn-outline-secondary"%>

        <% end %>
      </div><!-- search & create/update artist //end -->

      <div class="col-md-12"></div>
        <div class="paginate">
          <%= paginate @artists %>
        </div>
      </div>

    </div><!-- .row //end -->

  </div><!-- .container-fluid //end -->
  
</div><!-- .container-fluid //end -->