config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "events#index"

  # setup events
  resources :events, only: [:index, :show] do

    # All posts of events ; like index
    collection do
      get :posts
    end

  end

  # setup user
  resources :users, only: [:show, :edit, :update]

  # setup interest
  resources :interests, only: [:create, :destroy] 

  # setup artist
  resources :artists, only: [:show] 

  # setup admin
  namespace :admin do
    root "events#index"
    resources :events, except: [:show, :new, :create] do 
      member do
        get :remove_artist
      end
    end
    
    resources :users, only: [:index, :destroy]
    resources :artists do 
      member do
        get :search
      end
    end
  end
  
end

app/views/shared/_event_list.html.erb
<div class="event">

  <%= link_to event_path(object) do %> 
    <!-- img //start -->
    <div class="img">
      <%= image_tag object.img, width: "250", height: "250", class: "rounded mx-auto d-block img-fluid" if object.img?%>
      <%= image_tag "https://scontent-tpe1-1.xx.fbcdn.net/v/t1.0-9/10440134_10152691357289305_1073162233428965026_n.png?_nc_cat=0&_nc_eui2=v1%3AAeEbw6x8pNWalSgC4utDLwPFCO9J9EKLN6IKoL1475gucM59_-u2ybhW6o5OeJ6d9kl1bFOc5CX24vmkoOda2HMaAW2F_HaM7LPklDc2LKhCNQ&oh=1fe6caba187d6b7a7d129e301d0d4800&oe=5B6932F1", class: "rounded mx-auto d-block img-fluid" unless object.img?%> 
    </div>
    <!-- img //end -->
  <% end %>

  <div class="date text-center">
    <%= object.date %>
    <span id="interest-<%= object.id %>" class="text-center">
      <%= render partial: "shared/interest", locals: {object: object} %>
    </span>
  </div>

  <div class="container-fluid text-center">
    <h6 class="text-center"><%= link_to object.title, event_path(object) %></h6>
    <div class="artist">演出者 <br />
      <% if object.artist %>
        <span><strong><%= link_to object.artist_name, artist_path(object.artist) %></strong></span>
      <% else %>
        <span><strong><%= object.artist_name %></strong></span>
      <% end %>
    </div>
    <% if flag %>
      <div class="place">地點 <br /><span><strong><%= render partial: "shared/location", locals: {object: object} %></strong></span></div>
     <% end %>
  </div>

</div>

app/views/shared/_interest.html.erb
<% if current_user %>
  <% if current_user.is_interested?(object) %>
    <%= link_to interest_path(object),remote: true, method: :delete, class: "unlike-btn" do %>
      ♥ <%= content_tag :span, object.interested_users.size , class: "badge badge-danger new" %>
    <% end %>
  <% else %>
    <%= link_to interests_path(event_id: object), remote: true, method: :post, class: "like-btn" do %>
      ♥ <%= content_tag :span, object.interested_users.size, class: "badge badge-dark" %>
    <% end %>
  <% end %>
<% else %>
    <%= link_to new_user_session_path, class: "like-btn" do %>
      ♥ <%= content_tag :span, object.interested_users.size, class: "badge badge-dark" %>
    <% end %>
<% end %>

app/views/shared/_location.html.erb
<% if object.stage == "The Wall Live House" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/THE+WALL+%E5%85%AC%E9%A4%A8/@25.0108389,121.5366885,15z/data=!4m5!3m4!1s0x0:0x8c72211550e38b60!8m2!3d25.0108389!4d121.5366885" %>
<% elsif object.stage == "Legacy 傳 音樂展演空間" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/%E5%82%B3%E9%9F%B3%E6%A8%82%E5%B1%95%E6%BC%94%E7%A9%BA%E9%96%93/@25.0450345,121.5272737,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a97b1a2206fd:0x9784ea2eb84f8a7f!8m2!3d25.0450297!4d121.5294624" %>
<% elsif object.stage == "Korner" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/Korner/@25.0109166,121.5344663,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a9f5598b0041:0x103925efc006361e!8m2!3d25.0109118!4d121.536655" %>
<% elsif object.stage == "Revolver" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/Revolver/@25.0342774,121.5151345,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a99efb8f0c29:0xa78aaaa598fb4dda!8m2!3d25.0342726!4d121.5173232" %>
<% elsif object.stage == "PIPE Live Music" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/%E6%B0%B4%E7%AE%A1%E9%9F%B3%E6%A8%82/@25.0106153,121.5267842,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a98cb364546b:0x1ffbe94b6e59ad8f!8m2!3d25.0106105!4d121.5289729" %>
<% elsif object.stage == "Legacy mini @ amba" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/Legacy+mini+@+amba/@25.0451665,121.503383,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a908d60729a1:0xe99bafeac726139e!8m2!3d25.0451617!4d121.5055717" %>
<% elsif object.stage == "永豐 Legacy Taipei 音樂展演空間" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/%E5%82%B3%E9%9F%B3%E6%A8%82%E5%B1%95%E6%BC%94%E7%A9%BA%E9%96%93/@25.0450345,121.5272737,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a97b1a2206fd:0x9784ea2eb84f8a7f!8m2!3d25.0450297!4d121.5294624" %>
<% elsif object.stage == "Legacy Taichung" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/Legacy+Taichung+%E5%82%B3+%E9%9F%B3%E6%A8%82%E5%B1%95%E6%BC%94%E7%A9%BA%E9%96%93/@24.1765738,120.6209723,17z/data=!3m1!4b1!4m5!3m4!1s0x34691601d2657983:0x5d5193db5f6f405a!8m2!3d24.1765689!4d120.623161" %>
<% elsif object.stage == "公館河岸留言" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/%E6%B2%B3%E5%B2%B8%E7%95%99%E8%A8%80%E9%9F%B3%E6%A8%82%E8%97%9D%E6%96%87%E5%92%96%E5%95%A1/@25.017094,121.5291246,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a98c0a8fe225:0x66fed055249d840f!8m2!3d25.0170892!4d121.5313133" %>
<% elsif object.stage == "河岸留言 音樂藝文咖啡" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/%E6%B2%B3%E5%B2%B8%E7%95%99%E8%A8%80%E9%9F%B3%E6%A8%82%E8%97%9D%E6%96%87%E5%92%96%E5%95%A1/@25.017094,121.5291246,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a98c0a8fe225:0x66fed055249d840f!8m2!3d25.0170892!4d121.5313133" %>
<% elsif object.stage == "台北 月見ル君想フ" %>
  <%= link_to object.stage , "https://www.google.com.tw/maps/place/%E5%8F%B0%E5%8C%97%E6%9C%88%E8%A6%8B%E3%83%AB%E5%90%9B%E6%83%B3%E3%83%95/@25.0288948,121.5234113,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a99b4aa98e07:0xb26fe62d3a4c92c9!8m2!3d25.02889!4d121.5256" %>
<% end %>

app/views/shared/_mail_events.html.erb
<div class="event text-center">

  <%= link_to event_url(object) do %> 
    <!-- img //start -->
    <div class="img">
      <%= image_tag object.img, width: "600", height: "mx-auto", class: "rounded mx-auto d-block img-fluid" if object.img?%>
      <%= image_tag "http://via.placeholder.com/600x300", class: "rounded mx-auto d-block img-fluid"  unless object.img?%> 
    </div>
    <!-- img //end -->
  <% end %>
  <div class="container-fluid text-center">
    <div class="artist">活動名稱 : <span><strong><%= object.title %></strong></span></div>
    <div class="artist">活動日期 : <span><strong><%= object.date %></strong></span></div>
    <div class="artist">演出者 : <span><strong><%= object.artist_name %></strong></span></div>
    
    <% if flag %>
      <div class="place">地點 : <span><strong><%= object.stage %></strong></span></div>
     <% end %>
  </div>

</div>
<br/>