config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "events#index"

  # setup events
  resources :events, only: [:index, :show] do

    # All posts of events ; like index
    collection do
      get :posts
    end

  end

  # setup user
  resources :users, only: [:show, :edit, :update]

  # setup interest
  resources :interests, only: [:create, :destroy] 

  # setup artist
  resources :artists, only: [:show] 

  # setup admin
  namespace :admin do
    root "events#index"
    resources :events, except: [:show, :new, :create] do 
      member do
        get :remove_artist
      end
    end
    
    resources :users, only: [:index, :destroy]
    resources :artists do 
      member do
        get :search
      end
    end
  end
  
end

app/models/event.rb
class Event < ApplicationRecord

  # 欄位驗證 :artist_name待補
  validates_presence_of :title, :date, :time, :stage

  # 一個event可以有很多筆被interest的資料
  has_many :interests, dependent: :destroy
  # 一個event可以被很多user interest
  has_many :interested_users, through: :interests, source: :user

  # 一個event可以有很多筆被view的資料
  has_many :views, dependent: :destroy
  # 一個event可以被很多user view
  has_many :viewed_users, through: :views, source: :user

  # 一個event可以有很多筆要notification的資料
  has_many :notifications, dependent: :destroy
  # 一個event可以對很多user送出notification
  has_many :notified_users, through: :notifications, source: :user

  # 一個活動目前設定只會顯示一筆藝人資料
  belongs_to :artist, optional: true

  # ransck
  STAGE = {
    'The Wall Live House': 'The Wall Live House',
    'Korner': 'Korner',
    'Revolver': 'Revolver',
    'PIPE Live Music': 'PIPE Live Music',
    'Legacy mini @ amba': 'Legacy mini @ amba',
    'Legacy 傳 音樂展演空間': 'Legacy 傳 音樂展演空間',
    '永豐 Legacy Taipei 音樂展演空間': '永豐 Legacy Taipei 音樂展演空間',
    'Legacy Taichung': 'Legacy Taichung',
    '公館河岸留言': '公館河岸留言',
    '河岸留言 音樂藝文咖啡': '河岸留言 音樂藝文咖啡',
    '台北 月見ル君想フ': '台北 月見ル君想フ'
  }

  CITY = {
    'Taichung': '台中',
    'Taipei': '台北',
  }

  def count_views
    self.views_count += 1
    self.save
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  
  before_action :set_event, only: [:edit, :update, :destroy, :remove_artist]

  ALLOW_QUERIES = %w[s artist_name_cont title_cont city_cont date_cont time_cont stage_eq stage_cont views_count interests_count detail_cont artist_name_or_title_or_city_or_detail_cont date_lteq date_gteq views_count_gteq interests_count_gteq updated_at].freeze

  def index
    @events = Event.all.order(date: :desc)
    # ransack
    @q = Event.ransack(ransack_params)
    @events = @q.result(distinct: true).order(updated_at: :desc).page(params[:page]).per(20)
  end

  def update
    if current_user.is_admin
      if @event.update_attributes(event_params)
        flash[:notice] = "Admin功能：更新活動頁面成功"
        redirect_to admin_events_path
      else
        render :action => :edit
      end
    else
      flash[:alert] = "非Admin，無此權限"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @event.destroy
  end

  def remove_artist
    @event.artist_name = nil
    @event.artist_id = nil
    @event.video = nil
    @event.spotify_artist_id = nil
    @event.save!
    redirect_back(fallback_location: root_path)
  end

  private 

  def ransack_params
    if params[:q].present?
      params.require(:q).permit(*ALLOW_QUERIES)
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:artist_name, :title, :date, :time, :stage, :video, :detail, :city, :stage, :spotify_artist_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  ALLOW_QUERIES = %w[s artist_name_cont title_cont city_cont date_cont time_cont stage_eq stage_cont views_count interests_count detail_cont artist_name_or_title_or_city_or_detail_or_stage_cont date_gteq date_lteq created_at city_eq].freeze

  def index
    # ransack
    @q = Event.ransack(ransack_params)
    @events = @q.result(distinct: true).order(date: :asc).page(params[:page]).per(12)

  end

  def show
    @event = Event.find(params[:id])

    # views count
    @event.count_views
    if current_user
      if current_user.viewed_events.include?(@event)
        @view = current_user.views.where(event_id: @event)
        @view.destroy_all
      end
      current_user.views.create(event_id: params[:id])
    end

    if @event.artist
      @artist = @event.artist
    else
      @artist = Artist.new
    end

  end

  def posts
    # ransack
    @q = Event.ransack(ransack_params)
    @events = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(5)
    @popular_events = Event.all.order(interests_count: :desc).limit(5)
  end

  private 

  def ransack_params
    if params[:q].present?
      params.require(:q).permit(*ALLOW_QUERIES)
    end
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_post.html.erb
        <% @events.each do |event| %>  
          <div class="post">
            <div class="row">
              <!-- 標題 -->
              <div class="col-md-3 pdate">
                <%= event.date %>
              </div>
              <div class="col-md-7">
                <div class="ptitle"><%= link_to event.title, event_path(event) %></div>
              </div>
              <div class="col-md-2 interest">
                <%= render partial: "shared/interest", locals: {object: event} %>
                <%= event.interests_count %>
              </div>

              <!-- 內容 -->
              <div class="col-md-8">
                <div id="carouselIndicators<%= event.id %>" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                    <% i = 0 %>
                    <!-- youtube -->
                    <% if event.video != nil %>
                      <div class="carousel-item active">
                        <iframe id="existing-iframe-example"
                                      width="500" height="350"
                                      src="<%= event.video %>"
                                      frameborder="0"
                                      style="border: none"
                                      class="musicpiece d-block w-100"
                              ></iframe>
                      </div>
                      <% i += 1 %>
                    <% end %>
                    <!-- spotify -->
                    <% if event.spotify_artist_id == nil %>
                      <% event.load_spotify_artist_id %>
                    <% end %>

                    <% if event.spotify_artist_id != nil %>
                      <div class="carousel-item <%= "active" if i == 0 %>">
                        <iframe src="https://open.spotify.com/embed/artist/<%= event.spotify_artist_id %>" width="500" height="350" frameborder="0" allowtransparency="true" allow="encrypted-media" class="musicpiece d-block w-100"></iframe>
                      </div>
                      <% i += 1 %>
                    <% end %>
                    <!-- event picture -->
                    <% if event.img != nil %>
                      <div class="carousel-item <%= "active" if i == 0 %>">
                        <%= image_tag event.img %> <!-- 大小: 500*370 -->
                      </div>
                      <% i += 1 %>
                    <% else %>
                      <div class="carousel-item <%= "active" if i == 0 %>">
                        <img class="musicpiece d-block w-100" src="http://via.placeholder.com/500x370">
                        <div class="carousel-caption">
                          <h3>表演封面</h3>
                        </div>
                      </div>
                      <% i += 1 %>
                    <% end %>
                  </div>

                  <% if i > 1 %>
                    <ol class="carousel-indicators">
                      <% for j in 0..(i-1) %>
                        <li data-target="#carouselIndicators<%= event.id %>" data-slide-to="<%= j %>" class="<%= "active" if j == 0 %>"></li>
                      <% end %>
                    </ol>
                  
                    <a class="carousel-control-prev" href="#carouselIndicators<%= event.id %>" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselIndicators<%= event.id %>" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  <% end %>
                </div>
              </div>

              <div class="col-md-4 post-info">
                <div class="event-info">演出者 <span><%= event.artist_name %></span></div>
                <div class="event-info">票價 <span></span></div>
                <div class="event-info">地點 <span><%= event.city %></span></div>
                <div class="event-info time">時間 
                  <% if event.time == nil %>
                    <span><%= event.time %></span>
                  <% elsif %>
                    <span><%= event.time.to_s.slice(11..15) %></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <% # current_post_id = event.id %>
        <% end %>

app/views/events/index.html.erb
<div class="container">
  <div class="col-md-12 offset-md-0">
    <div class="row">

      <!-- ransack //start -->
      <div class="container-fluid col-12" id="event-filter">
        <%= search_form_for @q, url: events_path do |f| %>

          <div class="form-row form-group text-center">

            <div class="col-md-3 col-sm-12">
              <div class="input-group mb-3">
                <%= f.select :stage_eq, Event::STAGE.map(&:reverse), prompt: "活動地點", include_blank: "所有活動地點" %>
              </div>
            </div>

            <div class="col-md-1 col-sm-12">
              <div class="input-group mb-3">
                <%= f.select :city_eq, Event::CITY.map(&:reverse), prompt: "城市", include_blank: "所有城市" %>
              </div>
            </div>

            <div class="search-date col-md-8 col-sm-12">
              <%= f.label :date, '起始日期:' %>
              <%= f.date_field :date_gteq, :value => Time.now.strftime("%Y-%m-%d"), class: "col-md-4 col-sm-12"%>

              <%= f.label :date, '至:' %>
              <%= f.date_field :date_lteq, class: "col-md-4 col-sm-12"%>
            </div>

            <div class="search-search col-md-8 col-sm-12">
              <%= f.search_field :artist_name_or_title_or_city_or_detail_or_stage_cont, placeholder: "搜尋演出的獨立音樂創作者、創作團體、活動、城市、地點或關鍵字", class: "form-control" %>
            </div>

            <div class="search-submit col-md-2 col-sm-12">
              <%= f.submit '搜尋', class: "btn btn-outline-dark form-control" %>
            </div>

            <!-- 排序 -->
            <div class="col-md-2 col-sm-12">
              <div class="dropdown show">
                <a class="btn btn-dark dropdown-toggle form-control text-center" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  排序
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item"><%= sort_link(@q, :views_count, "依瀏覽數排序", default_order: :desc)%>
                  <a class="dropdown-item"><%= sort_link(@q, :date, "依活動日期排序", default_order: :desc) %></a>
                  <a class="dropdown-item"><%= sort_link(@q, :interests_count, "依收藏數排序", default_order: :desc) %></a>
                  <a class="dropdown-item"><%= sort_link(@q, :created_at, "依平台發佈時間排序", default_order: :desc) %></a>
                </div>
              </div>

            </div>

          </div>
        <% end %> <!-- search_form_for //end -->
        <hr>
      </div>
      <!-- ransack //end -->

      <div class="col-md-12"></div>

      <% @events.each do |event| %>
        <div class="col-lg-3 col-md-4 col-sm-6">

          <%= render partial: "shared/event_list", locals: {object: event, flag: true} %>

        </div>
      <% end %>

      <div class="col-md-12"></div>

      <div class="paginate">
        <%= paginate @events %>
      </div>

    </div>
  </div>
</div>

app/views/events/posts.html.erb
<div class="container">
  <div class="col-md-12 offset-md-0 container-fluid">

    <div class="row">

      <!-- ransack //start -->
      <div class="container-fluid col-12" id="event-filter">

        <%= search_form_for @q, url: posts_events_path do |f| %>

          <div class="form-row form-group text-center">

            <div class="col-md-3 col-sm-12">
              <div class="input-group mb-3">
                <%= f.select :stage_eq, Event::STAGE.map(&:reverse), prompt: "活動地點", include_blank: "所有活動地點" %>
              </div>
            </div>

            <div class="col-md-1 col-sm-12">
              <div class="input-group mb-3">
                <%= f.select :city_eq, Event::CITY.map(&:reverse), prompt: "城市", include_blank: "所有城市" %>
              </div>
            </div>

            <div class="search-date col-md-8 col-sm-12">
              <%= f.label :date, '起始日期:' %>
              <%= f.date_field :date_gteq, :value => Time.now.strftime("%Y-%m-%d"), class: "col-md-4 col-sm-12"%>

              <%= f.label :date, '至:' %>
              <%= f.date_field :date_lteq, class: "col-md-4 col-sm-12"%>
            </div>

            <div class="search-search col-md-8 col-sm-12">
              <%= f.search_field :artist_name_or_title_or_city_or_detail_or_stage_cont, placeholder: "搜尋演出的獨立音樂創作者、創作團體、活動、城市、地點或關鍵字", class: "form-control" %>
            </div>

            <div class="search-submit col-md-2 col-sm-12">
              <%= f.submit '搜尋', class: "btn btn-outline-dark form-control" %>
            </div>

            <!-- 排序 -->
            <div class="col-md-2 col-sm-12">
              <div class="dropdown show">
                <a class="btn btn-dark dropdown-toggle form-control text-center" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  排序
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item"><%= sort_link(@q, :views_count, "依瀏覽數排序", default_order: :desc)%>
                  <a class="dropdown-item"><%= sort_link(@q, :date, "依活動日期排序", default_order: :desc) %></a>
                  <a class="dropdown-item"><%= sort_link(@q, :interests_count, "依收藏數排序", default_order: :desc) %></a>
                  <a class="dropdown-item"><%= sort_link(@q, :created_at, "依平台發佈時間排序", default_order: :desc) %></a>
                </div>
              </div>

            </div>

          </div>
        <% end %>
        <hr>
      </div>
      <!-- ransack //end -->

      <div class="col-md-12"></div>

      <div class="col-lg-9 col-md-9 col-sm-12 w-100">
        <% @events.each do |event| %>
          <div class="post">
            <div class="row">
              <!-- 標題 -->
              <div class="col-12 text-center phead">
                <span class="col-md-3 pdate">
                  <%= event.date %>
                </span>
                <span class="col-md-8 ptitle">
                  <br /><%= link_to event.title, event_path(event)%>
                </span>
              </div>

              <!-- 內容 -->
              <div class="col-md-8">
                <div id="carouselIndicators<%= event.id %>" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                    <% i = 0 %>
                    <!-- youtube -->
                    <% if event.video.present? %>
                      <div class="carousel-item active">
                        <iframe id="existing-iframe-example"
                                      width="500" height="350"
                                      src="<%= event.video %>"
                                      frameborder="0"
                                      style="border: none"
                                      class="musicpiece d-block"
                                      allowfullscreen
                              ></iframe>
                      </div>
                      <% i += 1 %>
                    <% end %>
                    <!-- spotify -->

                    <% if event.spotify_artist_id.present? %>
                      <div class="carousel-item <%= "active" if i == 0 %>">
                        <iframe src="https://open.spotify.com/embed/artist/<%= event.spotify_artist_id %>" width="500" height="350" frameborder="0" allowtransparency="true" allow="encrypted-media" class="musicpiece d-block w-100"></iframe>
                      </div>
                      <% i += 1 %>
                    <% end %>
                    <!-- event picture -->
                    
                    <% if event.img.present? %>
                      <div class="carousel-item <%= "active" if i == 0 %>">
                        <%= image_tag event.img ,class: "musicpiece rounded mx-auto d-block img-fluid" %>
                      </div>
                      <% i += 1 %>
                    <% else %>
                      <div class="carousel-item <%= "active" if i == 0 %>">
                        <img class="musicpiece rounded mx-auto d-block img-fluid" src="https://scontent-tpe1-1.xx.fbcdn.net/v/t1.0-9/10440134_10152691357289305_1073162233428965026_n.png?_nc_cat=0&_nc_eui2=v1%3AAeEbw6x8pNWalSgC4utDLwPFCO9J9EKLN6IKoL1475gucM59_-u2ybhW6o5OeJ6d9kl1bFOc5CX24vmkoOda2HMaAW2F_HaM7LPklDc2LKhCNQ&oh=1fe6caba187d6b7a7d129e301d0d4800&oe=5B6932F1">
                        <div class="carousel-caption">
                        </div>
                      </div>
                      <% i += 1 %>
                    <% end %>
                    

                  </div> <!-- .carousel-inner//end -->

                  <% if i > 1 %>
                    <ol class="carousel-indicators">
                      <% for j in 0..(i-1) %>
                        <li data-target="#carouselIndicators<%= event.id %>" data-slide-to="<%= j %>" class="<%= "active" if j == 0 %>"></li>
                      <% end %>
                    </ol>
                  
                    <a class="carousel-control-prev" href="#carouselIndicators<%= event.id %>" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselIndicators<%= event.id %>" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  <% end %>
                </div>
              </div>

              <div class="col-md-4 post-info">
                <div class="event-info">演出者 
                  <% if event.artist %>
                    <span><strong><%= link_to event.artist_name, artist_path(event.artist) %></strong></span>
                  <% else %>
                    <span><strong><%= event.artist_name %></strong></span>
                  <% end %>
                </div>
                <div class="event-info">城市 <span><%= event.city %></span></div>
                <div class="event-info">地點 <span><%= render partial: "shared/location", locals: {object: event} %></span></div>
                <div class="event-info time">時間 
                  <% if event.time == nil %>
                    <span><%= event.time %></span>
                  <% elsif %>
                    <span><%= event.time.slice(0..4) %></span>
                  <% end %>
                </div>
                <div class="event-info">收藏 
                  <span class="interest text-center">
                    <span id="interest-<%= event.id %>">
                      <%= render partial: "shared/interest", locals: {object: event} %>
                    </span>
                  </span>
                </div>

              </div>
            </div>
          </div>
        <% end %>
      </div> 

      <div class="col-lg-3 col-md-3 col-sm-0">
        <h4>熱門活動</h4><br>
        <% @popular_events.each do |event| %>
          <%= render partial: "shared/event_list", locals: {object: event, flag: false} %>
        <% end %>
      </div>

      <div class="col-md-12"></div>
        <div class="paginate">
          <%= paginate @events %>
        </div>
      </div>
  
  </div>
</div>

app/views/events/show.html.erb
<div class="container-fluid">
  <div class="col-md-10 offset-md-1">
    <div class="row">
      

      <!-- img //start -->
      <div class="col-lg-6 col-md-12 img">
        <%= image_tag @event.img, width: "400", height: "300",class: "rounded mx-auto d-block img-fluid" if @event.img? %>
        <%= image_tag "https://scontent-tpe1-1.xx.fbcdn.net/v/t1.0-9/10440134_10152691357289305_1073162233428965026_n.png?_nc_cat=0&_nc_eui2=v1%3AAeEbw6x8pNWalSgC4utDLwPFCO9J9EKLN6IKoL1475gucM59_-u2ybhW6o5OeJ6d9kl1bFOc5CX24vmkoOda2HMaAW2F_HaM7LPklDc2LKhCNQ&oh=1fe6caba187d6b7a7d129e301d0d4800&oe=5B6932F1", width: "400", height: "300", class: "rounded mx-auto d-block img-fluid"  unless @event.img? %> 
      </div><!-- img //end -->

      <div class="col-lg-6 col-md-12 text-center">
        <span class="text-center">
          <h5 class="event-date col-12">
            <span class="text-left"><%= @event.date %></sapn>
            <span id="interest-<%= @event.id %>">
              <%= render partial: "shared/interest", locals: {object: @event} %>
            </span>
          </h5>
        </span>
        
        <h5 class="event-title"><%= @event.title %></h5>
        <div class="event-info">演出者 
          <% if @event.artist != nil && @event.artist != "" %>
            <span><%= link_to @event.artist_name, artist_path(@event.artist) %></span>
          <% elsif %>
            <span><%= @event.artist_name %></span>
          <% end %>
        </div>
        <!-- <div class="event-info">票價 <span></span></div> -->
        <div class="event-info">城市 <span><%= @event.city %></span></div>
        <div class="event-info">地點 <span><%= render partial: "shared/location", locals: {object: @event} %></span></div>
        <div class="event-info time">時間 
          <% if @event.time == nil %>
            <span><%= @event.time %></span>
          <% elsif %>
            <span><%= @event.time.slice(0..4) %></span>
          <% end %>
        </div>
        <!-- admin: edit -->
        <% if current_user %>
          <% if current_user.is_admin %>
            <%= link_to '編輯', edit_admin_event_path(@event), class: "btn btn-outline-primary" %>
            <%= link_to '清除演出者資料', remove_artist_admin_event_path(@event), class: "btn btn-outline-primary" %>
          <% end %>
        <% end %>

      </div>

      <div class="col-md-12"><hr id="event-hr"></div>
      <div class="col-md-12"><h3 class="event-artist"><%= @event.artist_name %></h3></div>
      
      
      <!-- details //start -->
      <% if current_user && current_user.is_admin == false %>
        <div class="col-md-7">
          <div class="subtitle"><i>樂團/表演介紹</i></div>
          <p class="event-detail" id="detail" ><%= @event.detail %></p>
        </div>
      <% elsif current_user && current_user.is_admin %>
        <div class="col-md-7">
          <div class="subtitle"><i>樂團/表演介紹</i></div>
          <p class="event-detail" id="detail" ><%= @event.detail %></p>
        </div>
      <% elsif @event.video.blank? && @event.spotify_artist_id.blank? %>
        <div class="col-md-12">
          <div class="subtitle"><i>樂團/表演介紹</i></div>
          <p class="event-detail" id="detail" ><%= @event.detail %></p>
        </div>
      <% else %>
        <div class="col-md-7">
          <div class="subtitle"><i>樂團/表演介紹</i></div>
          <p class="event-detail" id="detail" ><%= @event.detail %></p>
        </div>
      <% end %>
      <!-- details //end -->

      <!-- YT&spotify //start -->
      <% if @event.video.present? || @event.spotify_artist_id.present? %>
        <div class="col-md-5">
          <div class="subtitle"><strong><i>作品欣賞</i></strong></div>
          <div class="row">

            <!-- YT //start -->
            <% if @event.video.present? %>
              <div class="col-md-12 col-sm-12 piece text-center">
                <div class="piece">【Youtube】</div>
                <iframe id="existing-iframe-example"
                        width="450" height="230"
                        src="<%= @event.video %>"
                        frameborder="0"
                        style="border: none"
                        allowfullscreen
                ></iframe>
              </div><br />
            <% end %>
            <!-- YT //end -->
            
            <!-- spotify //start -->
            <% if  @event.spotify_artist_id.present? %> 
            <!-- 辨識有無spotify作品 //start-->
              <div class="col-md-12 col-sm-12 piece text-center">
                <div class="piece">【Spotify】</div>

                  <!-- iframe of spotify follow button -->
                  <iframe src="https://open.spotify.com/follow/1/?uri=spotify:artist:<%= @event.spotify_artist_id %>&size=detail&theme=light" width="300" height="56" scrolling="no" frameborder="0" style="border:none; overflow:hidden;" allowtransparency="true"></iframe>
                  <hr>

                  <!-- iframe of spotify playlist -->
                  <iframe src="https://open.spotify.com/embed/artist/<%= @event.spotify_artist_id %>" width="260" height="350" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

              </div>
            <% end %><!-- 辨識有無spotify作品 //end-->
            <!-- spotify //end -->
          </div>
            
          <!-- admin edit YT & Spotify //start -->
          <% if current_user %>
            <% if current_user.is_admin && @event.artist %>
            
              <div class="col-12 text-center">
                <br /><hr>
                <span class="text-muted"><strong>更新演出者Stream資料</strong></span>
                <br /><br />

                <%= form_for [:admin, @event.artist ] do |f| %>
                  <div class="form-group">
                    <%= f.text_field :name, placeholder: "Artist Name",  class: "form-control" %><br />
                    <%= f.text_field :artist_video, placeholder: "Artist Youtube Video",  class: "form-control" %><br />
                    <%= f.text_field :artist_spotify_id, placeholder: "Artist Spotify ID",  class: "form-control" %><br />
                  </div>
                  <div class="text-center">
                    <%= f.submit class: "btn btn-outline-secondary" %><br />
                    <br />
                    <%= f.button "取消變更", type: :reset, class: "btn btn-outline-secondary" %><br /><br />
                    <%= link_to "重新取得Stream Data", search_admin_artist_path(@event.artist), class: "btn btn-outline-secondary" %><br />
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end%>
          <br />
          <!-- admin edit YT & Spotify //end -->

        </div>
        <!-- YT&spotify //end -->

      <% else %>
        <!-- admin edit YT & Spotify //start -->
        <% if current_user %>
          
          <% if current_user.is_admin %>

            <% if @event.artist %>
              <!-- admin edit YT & Spotify //start -->
              <% if current_user %>
                <% if current_user.is_admin && @event.artist %>
                
                  <div class="col-md-5 col-sm-12 text-center">
                    <br /><hr>
                    <span class="text-muted"><strong>更新演出者Stream資料</strong></span>
                    <br /><br />

                    <%= form_for [:admin, @event.artist ] do |f| %>
                      <div class="form-group">
                        <%= f.text_field :name, placeholder: "Artist Name",  class: "form-control" %><br />
                        <%= f.text_field :artist_video, placeholder: "Artist Youtube Video",  class: "form-control" %><br />
                        <%= f.text_field :artist_spotify_id, placeholder: "Artist Spotify ID",  class: "form-control" %><br />
                      </div>
                      <div class="text-center">
                        <%= f.submit class: "btn btn-outline-secondary" %><br />
                        <br />
                        <%= f.button "取消變更", type: :reset, class: "btn btn-outline-secondary" %><br /><br />
                        <%= link_to "重新取得Stream Data", search_admin_artist_path(@event.artist), class: "btn btn-outline-secondary" %><br />
                      </div>
                    <% end %>
                  </div>
                <% end %>
              <% end%>
              <br />
              <!-- admin edit YT & Spotify //end -->
            <% else %>
              <div class="col-md-5 col-sm-12 text-center">
                <br /><hr>
                <span class="text-muted"><strong>新增藝人</strong></span> 
                <br /><br />

                <%= form_for [:admin, @artist ] do |f| %>
                  <div class="form-group">
                    <%= f.text_field :name, placeholder: "Artist Name",  class: "form-control" %><br />
                  </div>
                  <div class="text-center">
                    <%= f.submit class: "btn btn-outline-secondary" %><br />
                    <br />
                    <%= f.button "取消變更", type: :reset, class: "btn btn-outline-secondary" %><br /><br />
                  </div>
                <% end %>
              </div>
            <% end %>

          <% end %>
      
        <% end%>
        <!-- admin edit YT & Spotify //end -->
        <br />
      <% end %>

    </div> <!-- .row //end -->
  </div>
</div>

<script>
  // 自動轉換detail中的連結位置為超連結
  $('p').each(function(){
   $(this).html( $(this).html().replace(/((http|https|ftp):\/\/[\w?=&.\/-;#~%-]+(?![\w\s?&.\/;#~%"=-]*>))/g, '<a href="$1">$1</a> ') );
  });
</script>